### PR TITLE
make it crash less on nodejs v6.3.1

### PR DESCRIPTION
**Pull request by stoto**
Changed obj.hasOwnProperty calls to Object.prototype.hasOwnProperty calls.

### CODE REVIEW

**Comment by Samistine** [comment]
Merge

**Comment by gshafer** [comment]
I have node v8.0.0. Still have the crash problem on post.
Can some post the steps required to fix this?
I tried making the edits suggested earlier but no joy.

**Comment by strank** [comment]
can confirm that this pull request just fixed a broken vanilla phant/vagrant install for me

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.

**Pull request closed without merging**
