### PR TITLE
Make tests pass, fix lint errors.

### PR DESCRIPTION
**Pull request by adewinter**
Super minor tweaks because the Travis CI build has been failing for 6 months.  This should fix it!

### CODE REVIEW

**Comment by adewinter** [comment]
Well.  For some reason the tests pass locally but not on Travis.  Investigating further.

**Comment by adewinter** [comment]
Ok! Travis CI build passing!

**Review by chaimleib — APPROVED** [review]

**Comment by adewinter** [comment]
@chaimleib what's the procedure for merging the code into master?   I don't have write access so doesn't look like I can do it myself...

**Comment by chaimleib** [comment]
I don't have access either. Someone from Sparkfun has to accept the PR and merge it.

**Comment by adewinter** [comment]
Paging: @toddtreece or @zinefer

**Pull request closed without merging**
